name: Deploy site to S3
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install && pnpm run build
      - run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
